"""
Drive Manager — Google Drive API v3 integration.

Uses a Service Account (preferred for automation) or OAuth2 token.
All uploads go to the configured GOOGLE_DRIVE_FOLDER_ID.
"""
from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Optional

from config import settings
from models.project import Project

logger = logging.getLogger(__name__)

_SCOPES = ["https://www.googleapis.com/auth/drive.file"]


class DriveManager:
    """Upload finished videos to Google Drive."""

    def __init__(self) -> None:
        self._service = None  # lazy-loaded

    def is_configured(self) -> bool:
        return bool(settings.google_service_account_file and
                    Path(settings.google_service_account_file).exists())

    def upload_video(
        self,
        project: Project,
        file_path: Optional[str] = None,
        folder_id: Optional[str] = None,
    ) -> Optional[str]:
        """
        Upload the project's final video to Drive.
        Returns the shareable link or None on failure.
        """
        video_path = Path(file_path or project.final_video_path or "")
        if not video_path.exists():
            logger.error("Video file not found: %s", video_path)
            return None

        service = self._get_service()
        if not service:
            return None

        target_folder = folder_id or settings.google_drive_folder_id
        file_name = f"{project.title}_{project.uuid[:8]}.mp4"

        logger.info("Uploading %s to Drive folder %s", file_name, target_folder)

        try:
            from googleapiclient.http import MediaFileUpload

            file_metadata = {
                "name": file_name,
                "parents": [target_folder] if target_folder else [],
            }
            media = MediaFileUpload(
                str(video_path),
                mimetype="video/mp4",
                resumable=True,
                chunksize=5 * 1024 * 1024,  # 5 MB chunks
            )

            request = service.files().create(
                body=file_metadata,
                media_body=media,
                fields="id, webViewLink",
            )

            response = None
            while response is None:
                status, response = request.next_chunk()
                if status:
                    pct = int(status.progress() * 100)
                    logger.debug("Drive upload progress: %d%%", pct)

            file_id   = response.get("id")
            view_link = response.get("webViewLink")

            # Make file readable by anyone with the link
            service.permissions().create(
                fileId=file_id,
                body={"type": "anyone", "role": "reader"},
            ).execute()

            project.drive_file_id = file_id
            project.drive_link    = view_link
            logger.info("Uploaded → %s", view_link)
            return view_link

        except Exception as e:
            logger.error("Drive upload failed: %s", e)
            return None

    def check_connection(self) -> bool:
        """Ping Drive API — used in health check."""
        service = self._get_service()
        if not service:
            return False
        try:
            service.about().get(fields="user").execute()
            return True
        except Exception:
            return False

    # ── Internals ──────────────────────────────────────────────────────────────

    def _get_service(self):
        if self._service:
            return self._service
        try:
            from google.oauth2 import service_account
            from googleapiclient.discovery import build

            sa_file = settings.google_service_account_file
            if not Path(sa_file).exists():
                # Fallback: try OAuth2 token.json
                return self._get_service_oauth()

            creds = service_account.Credentials.from_service_account_file(
                sa_file, scopes=_SCOPES
            )
            self._service = build("drive", "v3", credentials=creds)
            return self._service

        except Exception as e:
            logger.error("Could not build Drive service: %s", e)
            return None

    def _get_service_oauth(self):
        """OAuth2 fallback using token.json (generated by setup_drive.py)."""
        try:
            from google.oauth2.credentials import Credentials
            from google.auth.transport.requests import Request
            from googleapiclient.discovery import build

            # Resolve token.json next to service account file, or in cwd
            sa_dir = Path(settings.google_service_account_file).parent \
                if settings.google_service_account_file else Path(".")
            token_path = sa_dir / "token.json"
            if not token_path.exists():
                token_path = Path("token.json")  # fallback to cwd

            creds = None
            if token_path.exists():
                creds = Credentials.from_authorized_user_file(str(token_path), _SCOPES)

            if not creds or not creds.valid:
                if creds and creds.expired and creds.refresh_token:
                    creds.refresh(Request())
                    token_path.write_text(creds.to_json())
                else:
                    logger.warning("OAuth2 token missing or invalid — run setup_drive.py")
                    return None

            self._service = build("drive", "v3", credentials=creds)
            return self._service
        except Exception as e:
            logger.warning("OAuth2 Drive fallback failed: %s", e)
            return None
